# /* ----  https://github.com/4ndr0666  ---- */
# /* wallust template - colors-hyprland */

$background = rgb(212424)
$foreground = rgb(D0EEE4)
$color0 = rgb(464A4A)
$color1 = rgb(0F1D1E)
$color2 = rgb(101C1F)
$color3 = rgb(221A28)
$color4 = rgb(221A29)
$color5 = rgb(476A68)
$color6 = rgb(5B9B86)
$color7 = rgb(B4DFD1)
$color8 = rgb(7E9C92)
$color9 = rgb(142628)
$color10 = rgb(162629)
$color11 = rgb(2E2336)
$color12 = rgb(2E2336)
$color13 = rgb(5F8D8A)
$color14 = rgb(7ACFB3)
$color15 = rgb(B4DFD1)
