-- File: hyprland.lua
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

local home = os.getenv("HOME")
package.path = package.path .. ";" .. home .. "/.config/hypr/?.lua;" .. home .. "/.config/hypr/?/init.lua"

-- Required configuration modules must fail loudly.  The migration is now
-- native Lua; silently swallowing require() failures creates a partial,
-- invalid compositor configuration that is difficult to diagnose.
local function source(module_name)
    return require(module_name)
end

-- User defaults must exist before any module that consumes them.
source("UserConfigs.01-UserDefaults")

-- Initial boot script (asynchronous hook; the script owns marker semantics).
hl.on("hyprland.start", function ()
    hl.exec_cmd(home .. "/.config/hypr/initial-boot.sh")
end)

-- Pre-configured keybinds
source("configs.Keybinds")

-- Load defaults, then user additions/overrides
source("configs.Startup_Apps")
source("configs.ENVariables")

-- Window Rules and Layer Rules
source("configs.WindowRules")

-- Default config for hypr
source("configs.SystemSettings")

-- User Overrides
source("UserConfigs.UserDecorations")
source("UserConfigs.UserAnimations")
source("UserConfigs.UserKeybinds")
source("UserConfigs.UserSettings")

-- Hardware & Workspaces (nwg-displays)
source("monitors")
source("workspaces")

-- User-owned workspace policy is loaded after generated workspace placement.
source("UserConfigs.WorkSpaceRules")
