-- File: monitors.lua
-- Generated by nwg-displays. Do not edit manually. (Ported to Lua)

hl.monitor({
    output = "desc:Hewlett Packard HP 23er 3CM944167G",
    mode = "1920x1080@60.0",
    position = "1920x176",
    scale = 1.0,
    bitdepth = 10
})

hl.monitor({
    output = "desc:Toshiba America Info Systems Inc TOSHIBA-TV 0x01010101",
    mode = "1920x1080@60.0",
    position = "0x0",
    scale = 1.0,
    bitdepth = 10
})
