-- File: workspaces.lua
-- Generated by nwg-displays on 2025-10-17 at 05:15:05. Do not edit manually.

-- workspace=1,monitor:desc:Toshiba America Info Systems Inc TOSHIBA-TV 0x01010101,default:true
hl.workspace_rule({ workspace = 1, monitor = "desc:Toshiba America Info Systems Inc TOSHIBA-TV 0x01010101", default = true })

-- workspace=2,monitor:desc:Hewlett Packard HP 23er 3CM944167G,default:false
hl.workspace_rule({ workspace = 2, monitor = "desc:Hewlett Packard HP 23er 3CM944167G", default = false })

-- workspace=3,monitor:desc:Toshiba America Info Systems Inc TOSHIBA-TV 0x01010101
hl.workspace_rule({ workspace = 3, monitor = "desc:Toshiba America Info Systems Inc TOSHIBA-TV 0x01010101" })

-- workspace=4,monitor:desc:Hewlett Packard HP 23er 3CM944167G
hl.workspace_rule({ workspace = 4, monitor = "desc:Hewlett Packard HP 23er 3CM944167G" })

-- workspace=5,monitor:desc:Toshiba America Info Systems Inc TOSHIBA-TV 0x01010101
hl.workspace_rule({ workspace = 5, monitor = "desc:Toshiba America Info Systems Inc TOSHIBA-TV 0x01010101" })

-- workspace=6,monitor:desc:Hewlett Packard HP 23er 3CM944167G
hl.workspace_rule({ workspace = 6, monitor = "desc:Hewlett Packard HP 23er 3CM944167G" })

-- workspace=7,monitor:desc:Toshiba America Info Systems Inc TOSHIBA-TV 0x01010101
hl.workspace_rule({ workspace = 7, monitor = "desc:Toshiba America Info Systems Inc TOSHIBA-TV 0x01010101" })

-- workspace=8,monitor:desc:Hewlett Packard HP 23er 3CM944167G
hl.workspace_rule({ workspace = 8, monitor = "desc:Hewlett Packard HP 23er 3CM944167G" })

-- workspace=9,monitor:desc:Toshiba America Info Systems Inc TOSHIBA-TV 0x01010101
hl.workspace_rule({ workspace = 9, monitor = "desc:Toshiba America Info Systems Inc TOSHIBA-TV 0x01010101" })

-- workspace=10,monitor:desc:Hewlett Packard HP 23er 3CM944167G
hl.workspace_rule({ workspace = 10, monitor = "desc:Hewlett Packard HP 23er 3CM944167G" })
