#!/usr/bin/env bash
set -Eeuo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
FILE="$ROOT/install-scripts/sddm_theme.sh"

[[ -f "$FILE" ]] || { printf '[FAIL] Missing SDDM theme installer.\n' >&2; exit 1; }
grep -q '^#!/usr/bin/env bash$' "$FILE"
grep -q '^set -Eeuo pipefail$' "$FILE"
grep -Fq 'source_theme="https://github.com/achrefbenmbarek1/terminal-inspired-sddm-theme.git"' "$FILE"
grep -Fq 'SDDM_THEME_REPOSITORY_REVISION="e0691c4f3a3cff22a3635045902b9fc949d6bbf5"' "$FILE"
grep -Eq '^SDDM_THEME_REPOSITORY_REVISION="[0-9a-f]{40}"$' "$FILE"
grep -Fq 'GIT_COMMAND_TIMEOUT=' "$FILE"
grep -Fq 'timeout --signal=TERM --kill-after=10s "$GIT_COMMAND_TIMEOUT" git clone' "$FILE"
grep -Fq 'checkout --detach "$SDDM_THEME_REPOSITORY_REVISION"' "$FILE"
grep -Fq 'ACTUAL_REVISION="$(git -C "$STAGED_THEME" rev-parse HEAD)"' "$FILE"
grep -Fq '[[ "$ACTUAL_REVISION" == "$SDDM_THEME_REPOSITORY_REVISION" ]]' "$FILE"
grep -Fq 'sudo -v' "$FILE"
grep -Fq 'TRANSACTION_DIR=' "$FILE"
grep -Fq 'trap cleanup EXIT INT TERM HUP' "$FILE"
grep -Fq 'COMMITTED=0' "$FILE"
grep -Fq 'COMMITTED=1' "$FILE"
grep -Fq 'sudo -n mv -- "$THEME_DEST" "$THEME_BACKUP"' "$FILE"
grep -Fq 'sudo -n mv -- "$STAGED_THEME" "$THEME_DEST"' "$FILE"
grep -Fq 'sudo -n rm -rf -- "$THEME_DEST"' "$FILE"
grep -Fq 'sudo -n mv -- "$THEME_BACKUP" "$THEME_DEST"' "$FILE"
grep -Fq 'SDDM_MODE=' "$FILE"
grep -Fq 'stat -c '\''%a'\'' -- "$SDDM_CONF"' "$FILE"
grep -Fq 'sudo -n cp -a -- "$SDDM_BACKUP" "$SDDM_CONF"' "$FILE"
grep -Fq 'sudo -n chmod -- "$SDDM_MODE" "$SDDM_CONF"' "$FILE"
grep -Fq 'sudo -n install -m 0644 -- "$SDDM_NEW" "$SDDM_CONF"' "$FILE"
grep -Fq 'sudo -n rm -rf -- "$TRANSACTION_DIR"' "$FILE"
grep -Fq '[[ -x "$STAGED_THEME/sessionsDetector.sh" ]]' "$FILE"
grep -Fq './sessionsDetector.sh' "$FILE"
grep -Fq '[[ -s "$STAGED_THEME/sessions.txt" ]]' "$FILE"
! grep -Fq 'https://github.com/4ndr0666/simple-sddm-2.git' "$FILE"
! grep -Fq 'git clone --depth 1 --no-tags "$source_theme" "$STAGED_THEME"' "$FILE"
! grep -Fq 'if git clone' "$FILE"
! grep -Fq 'sudo sed -i' "$FILE"
! grep -Fq 'sudo tee' "$FILE"
! grep -Fq '|| true' "$FILE"

bash -n "$FILE"
printf '[PASS] SDDM theme dependency is canonical, pinned, bounded, staged, transactional, rollback-safe, and session-aware.\n'
